// Turns data/restaurants.json (research output) into js/data/restaurants.gen.js.
// Validates, slugs ids, dedupes, and prints a coverage summary.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const raw = JSON.parse(readFileSync(join(root, 'data/restaurants.json'), 'utf8'))

const slug = (s) =>
  String(s).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

const seen = new Set()
const out = []
let dropped = 0

for (const r of raw.restaurants) {
  const ok =
    r.name && r.address && r.cuisine && r.signatureDish?.name &&
    Number.isFinite(r.lat) && Number.isFinite(r.lng) &&
    r.lat > 36.8 && r.lat < 38.3 && r.lng > -122.9 && r.lng < -121.4 &&
    Number.isFinite(r.rating)
  if (!ok) { dropped++; console.warn('drop (invalid):', r.name); continue }
  let id = slug(r.name)
  if (seen.has(id)) id = `${id}-${slug(r.city || r.neighborhood || 'x')}`
  if (seen.has(id)) { dropped++; console.warn('drop (dupe):', r.name); continue }
  seen.add(id)
  const hours = Array.isArray(r.hours)
    ? r.hours
        .filter((h) => Array.isArray(h) && h.length === 3 && h[0] >= 0 && h[0] <= 6 && /^\d{2}:\d{2}$/.test(h[1]) && /^\d{2}:\d{2}$/.test(h[2]))
        .slice(0, 14)
    : undefined
  // Normalize addresses to bare street form (some late entries embed ", City, CA zip").
  const address = String(r.address).replace(/,\s*[A-Za-z .]+,?\s*CA\s*\d{0,5}\s*$/i, '').trim()
  out.push({
    id,
    name: r.name,
    cuisine: r.cuisine,
    neighborhood: r.neighborhood || '',
    city: r.city || '',
    address,
    lat: +(+r.lat).toFixed(5),
    lng: +(+r.lng).toFixed(5),
    rating: Math.min(5, Math.max(3, +(+r.rating).toFixed(1))),
    ratingCount: Math.max(1, Math.round(r.ratingCount || 100)),
    price: Math.min(4, Math.max(1, Math.round(r.price || 2))),
    emoji: r.emoji || '🍽️',
    signatureDish: { name: r.signatureDish.name, description: r.signatureDish.description || '' },
    menu: (r.menu || [])
      .filter((m) => String(m.name).trim().toLowerCase() !== String(r.signatureDish.name).trim().toLowerCase())
      .slice(0, 5)
      .map((m) => ({ name: m.name, price: m.price || '', description: m.description || '' })),
    tags: [...new Set(r.tags || [])].slice(0, 8),
    why: r.why || '',
    ...(hours && hours.length ? { hours } : {}),
    ...(r.mapsUrl ? { mapsUrl: r.mapsUrl } : {}),
    ...(r.priceRange ? { priceRange: r.priceRange } : {}),
    ...(r.verified ? { verified: true } : {}),
  })
}

const meta = {
  city: 'SF Bay Area',
  generatedAt: raw.generatedAt || new Date().toISOString().slice(0, 10),
  ...(raw.verifiedAt ? { verifiedAt: raw.verifiedAt } : {}),
  refreshMonths: 2,
  count: out.length,
}

writeFileSync(
  join(root, 'js/data/restaurants.gen.js'),
  `// GENERATED by scripts/integrate_data.mjs — do not edit by hand.\n` +
    `export const DATA_META = ${JSON.stringify(meta)}\n\n` +
    `export const RESTAURANTS = ${JSON.stringify(out, null, 1)}\n`
)

const byCuisine = {}
const byCity = {}
for (const r of out) {
  byCuisine[r.cuisine] = (byCuisine[r.cuisine] || 0) + 1
  byCity[r.city] = (byCity[r.city] || 0) + 1
}
console.log(`kept ${out.length}, dropped ${dropped}`)
console.log('cities:', JSON.stringify(byCity))
console.log('cuisines:', JSON.stringify(byCuisine))
